exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

title: Qinkai Wu's web
url: "https://wu-2018.github.io" # the base hostname & protocol for your site
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-seo-tag

# Google analytics
ga_tracking_id: "UA-128570432-1"

contact_post: "https://formspree.io/wuqinkai@genomics.cn"

disqus: True
